from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet

# --- Task 1: API Routing Logic ---

# 1. Creating a DefaultRouter instance to automatically handle URL patterns
# It generates standard CRUD routes (GET, POST, PUT, DELETE) for our ViewSets.
router = DefaultRouter()

# 2. Registering the ViewSets with the Router
# 'posts' -> handles all blog post related requests
router.register(r'posts', PostViewSet)
# 'comments' -> handles all comment related requests
router.register(r'comments', CommentViewSet)

# 3. Defining the urlpatterns for the blog app
# This includes all the routes generated by the router above.
urlpatterns = [
    # The empty string '' means these routes start directly from 'api/blog/'
    path('', include(router.urls)),
]